# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  changelog:
    sources: [./CHANGELOG.yml]
    generates: [./CHANGELOG.md]
    cmds:
      - changelord print > CHANGELOG.md
  test: vitest run

  build:
    sources: ["src/**"]
    generates: ["esm/**"]
    deps: [test]
    cmds:
      - rm -fr esm/
      - tsc -p tsconfig.json

  prepRelease:
    deps: [changelog, build]
    preconditions:
      - sh: git branch | grep '* main'
        msg: not on main
      - sh: git is-clean
        msg: stuff not commited
    cmds:
      - npm pack

  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
