# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  changelog:
    sources: [./CHANGELOG.yml]
    generates: [./CHANGELOG.md]
    cmds:
      - changelord print > CHANGELOG.md
  test: vitest run
  build:
    deps: [test]
    cmds:
      - rm -fr esm/
      - tsc -p tsconfig.json
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
