# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  test: vitest run
  build:
    deps: [test]
    cmds:
      - rm -fr esm/
      - tsc -p tsconfig.json
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
